language: ruby

os: linux
sudo: required
dist: trusty
compiler: gcc
cache:
 - apt
 - ccache

# In addition to the default settings (above), add test runs using the Travis rvm ruby binaries.
matrix:
  include:
    - env: USE_QT4=1
    - rvm: 1.9.3
      env: USE_RVM=1
    - rvm: 2.1.2
      env: USE_RVM=1
    - rvm: 2.2.3
      env: USE_RVM=1

before_install:
 - sudo apt-get update
 - sudo apt-get --yes install ruby-all-dev rake cmake pkg-config g++ libfftw3-dev libffi-dev
 - |
   if [[ $USE_QT4 ]]
   then
      sudo apt-get --yes install libqscintilla2-dev qt4-dev-tools qt4-default libqwt-dev libboost-all-dev
   else
      sudo add-apt-repository ppa:latthias/qgis-travis-deps -y
      sudo apt-get update -q
      sudo apt-get --yes install libqt5scintilla2-dev qtbase5-dev qttools5-dev qttools5-dev-tools qt5-default libqt5opengl5-dev libqt5svg5-dev libqwt-qt5-dev libboost-all-dev
   fi

script:
 - set -e
# The | starts a multiline YAML entry
 - |
   if [[ $USE_RVM ]]
   then
     # This compiles the gems and runs the Sonic Pi test suite with the ruby installed through Travis's rvm
     echo ""
     echo "***********************************"
     echo "* Compiling the vendor/ ruby gems *"
     echo "***********************************"
     cd $TRAVIS_BUILD_DIR
     rake compile_gems
     echo ""
     echo "***********************************"
     echo "* Running the Sonic Pi test suite *"
     echo "***********************************"
     cd $TRAVIS_BUILD_DIR/app/server/sonicpi
     rake test
   else
     # This compiles the gems and runs the Sonic Pi test suite for all ruby versions in Ubuntu Trusty (1.9.1 and 2.0.0)
     echo ""
     echo "***********************************"
     echo "* Compiling the vendor/ ruby gems *"
     echo "***********************************"
     cd $TRAVIS_BUILD_DIR
     /usr/bin/ruby -e 'require "ruby_debian_dev"; include RubyDebianDev; SUPPORTED_RUBY_VERSIONS.each { |v, b| system(b + " /usr/bin/rake compile_gems") or raise ("ruby gem compile failed for " + v) ; system(b + " /usr/bin/rake clean_gems") }'
     echo ""
     echo "***********************************"
     echo "* Running the Sonic Pi test suite *"
     echo "***********************************"
     cd $TRAVIS_BUILD_DIR/app/server/sonicpi
     /usr/bin/ruby -e 'require "ruby_debian_dev"; include RubyDebianDev; SUPPORTED_RUBY_VERSIONS.each { |v, b| system(b + " /usr/bin/rake test") or raise ("test failed for " + v) }'
     echo ""
     echo "***********************************"
     if [[ $USE_QT4 ]]
     then
       echo "* Compiling Sonic Pi GUI with Qt4 *"
     else
       echo "* Compiling Sonic Pi GUI with Qt5 *"
     fi
     echo "***********************************"
     # Travis installs a rvm ruby version locally and overrides the rake path.
     # The following makes sure that we're using the installed ruby version that comes with Ubuntu Trusty.
     cd $TRAVIS_BUILD_DIR
     /usr/bin/ruby -e 'require "ruby_debian_dev"; include RubyDebianDev; SUPPORTED_RUBY_VERSIONS.first { |v, b| system(b + " /usr/bin/rake compile_qt_gui") or raise ("test failed for " + v) }'
   fi
