language: ruby

os: linux
sudo: required

matrix:
    include:
        - dist: trusty
        - dist: xenial

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:latthias/qgis-travis-deps'
    packages:
    - ruby-all-dev
    - rake
    - cmake
    - pkg-config
    - g++
    - libfftw3-dev
    - libffi-dev
    - libqt5scintilla2-dev
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools
    - qt5-default
    - libqt5opengl5-dev
    - libqt5svg5-dev
    - libqwt-qt5-dev
    - libboost-all-dev
    - libasound2-dev
    - erlang

compiler: gcc

cache:
 - apt
 - ccache

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0

before_install:
 - |
    set -e # Fail on error
    # Build and install aubio 0.4.4
    wget http://aubio.org/pub/aubio-0.4.4.tar.bz2
    tar xvjf aubio-0.4.4.tar.bz2
    cd aubio-0.4.4
    ./waf configure build
    sudo ./waf install

    # Install ruby gems required for build
    gem install rake bundler fileutils kramdown gettext

script:
 - set -e
# the | starts a multiline YAML entry
 - |
    echo ""
    echo "***********************************"
    echo "* Building Sonic Pi               *"
    echo "***********************************"
    cd $TRAVIS_BUILD_DIR
    rake build

    echo ""
    echo "***********************************"
    echo "* Running the Sonic Pi test suite *"
    echo "***********************************"
    cd $TRAVIS_BUILD_DIR/app/server/ruby/test
    rake test
