language: ruby

os: linux
sudo: false
dist: bionic
addons:
  apt:
    update: true
    packages:
    - ruby-all-dev
    - rake
    - cmake
    - pkg-config
    - g++
    - libfftw3-dev
    - libffi-dev
    - libqt5scintilla2-dev
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools
    - qt5-default
    - libqt5opengl5-dev
    - libqt5svg5-dev
    - libqwt-qt5-dev
    - libboost-all-dev
    - libaubio-dev
compiler: gcc

cache:
  - apt
  - ccache

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

before_install:
  - gem install bundler
  - cd $TRAVIS_BUILD_DIR/app/server/ruby && bundler lock && bundle install --path vendor --jobs 4 --retry 4

script:
  - set -e
  # the | starts a multiline YAML entry
  - |
    echo ""
    echo "***********************************"
    echo "* Running the Sonic Pi test suite *"
    echo "***********************************"
    cd $TRAVIS_BUILD_DIR/app/server/ruby
    bundle exec rake test
