language: ruby

os: linux
sudo: required
dist: xenial
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:latthias/qgis-travis-deps'
    packages:
    - ruby-all-dev
    - rake
    - cmake
    - pkg-config
    - g++
    - libfftw3-dev
    - libffi-dev
    - libqt5scintilla2-dev
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools
    - qt5-default
    - libqt5opengl5-dev
    - libqt5svg5-dev
    - libboost-all-dev
compiler: gcc

cache:
 - apt
 - ccache

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0

before_install:
  - # Install aubio
  - wget http://aubio.org/pub/aubio-0.4.4.tar.bz2
  - tar xvjf aubio-0.4.4.tar.bz2
  - cd aubio-0.4.4
  - ./waf configure build
  - sudo ./waf install
  - # Install bundler 2 and rake
  - yes | gem update --system --force # Bundler 2 requires RubyGems v2.5.0 or above; update rubygems to make sure it's at least v2.5.0
  - gem install bundler rake

script:
 - set -e
# the | starts a multiline YAML entry
 - |
    # this compiles the gems and runs the Sonic Pi test suite with the ruby installed through Travis's rvm
    echo ""
    echo "***********************************"
    echo "* Bundle required ruby gems       *"
    echo "***********************************"
    cd $TRAVIS_BUILD_DIR/app/server/ruby/
    bundle config --local path "vendor/bundle"
    bundle install --with=:default,:development
 - |
    echo ""
    echo "***********************************"
    echo "* Running the Sonic Pi test suite *"
    echo "***********************************"
    cd $TRAVIS_BUILD_DIR/app/server/ruby/test
    rake test
